"use client";

// src/app/haberler/page.tsx
// 2000+ Gündem İngilizce Haberler Kütüphanesi + Sesli Dinleme (Kadın/Erkek) + Arka Planda Çalma + Tıklanabilir Çeviri

import React, { useState, useEffect, useRef } from "react";
import Link from "next/link";
import {
  Newspaper,
  Volume2,
  Pause,
  Play,
  Languages,
  Headphones,
  Search,
  Sparkles,
  Bookmark,
  Calendar,
  Clock,
  ArrowRight,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { addStudentXp } from "@/lib/progress-store";

interface NewsArticle {
  id: string;
  category: "Teknoloji" | "Bilim" | "İklim & Çevre" | "Ekonomi" | "Kültür" | "Sağlık";
  titleEn: string;
  titleTr: string;
  date: string;
  readTime: string;
  cefrLevel: "B1" | "B2" | "C1" | "C2";
  paragraphs: {
    en: string;
    tr: string;
  }[];
  keyVocab: { en: string; tr: string }[];
}

const SAMPLE_NEWS: NewsArticle[] = [
  {
    id: "news-01",
    category: "Teknoloji",
    titleEn: "Breakthrough in Quantum Computing Achieves Millisecond Coherence",
    titleTr: "Kuantum Hesaplamada Çığır Açan Gelişme: Milisaniyelik Tutarlılığa Ulaşıldı",
    date: "30 Eylül 2026",
    readTime: "3 dk okuma",
    cefrLevel: "C1",
    paragraphs: [
      {
        en: "Researchers at international laboratories have demonstrated a scalable quantum processor capable of maintaining coherent quantum states for over one millisecond at room temperature.",
        tr: "Uluslararası laboratuvarlardaki araştırmacılar, oda sıcaklığında bir milisaniyeden daha uzun süre tutarlı kuantum durumlarını koruyabilen ölçeklenebilir bir kuantum işlemcisi geliştirdiler.",
      },
      {
        en: "This technological leap is anticipated to revolutionize cybersecurity protocols, computational biochemistry, and complex meteorological forecasting models within the next decade.",
        tr: "Bu teknolojik sıçramanın önümüzdeki on yıl içinde siber güvenlik protokollerinde, hesaplamalı biyokimyada ve karmaşık meteorolojik tahmin modellerinde devrim yaratması bekleniyor.",
      },
      {
        en: "Academic observers emphasize that overcoming thermal noise has historically represented the most formidable impediment in practical quantum hardware deployment.",
        tr: "Akademik gözlemciler, termal gürültünün üstesinden gelmenin, pratik kuantum donanımı kurulumunda tarihsel olarak en zorlu engeli temsil ettiğini vurguluyorlar.",
      },
    ],
    keyVocab: [
      { en: "scalable", tr: "ölçeklenebilir" },
      { en: "coherent state", tr: "tutarlı kuantum durumu" },
      { en: "formidable impediment", tr: "zorlu engel" },
    ],
  },
  {
    id: "news-02",
    category: "İklim & Çevre",
    titleEn: "Global Reforestation Initiative Exceeds Ten Billion Tree Milestone",
    titleTr: "Küresel Ağaçlandırma Girişimi On Milyar Ağaç Eşiğini Aştı",
    date: "29 Eylül 2026",
    readTime: "4 dk okuma",
    cefrLevel: "B2",
    paragraphs: [
      {
        en: "A collaborative consortium of environmental organizations and governmental agencies confirmed that their combined reforestation efforts have planted ten billion indigenous saplings across degraded ecosystems.",
        tr: "Çevre örgütleri ve hükümet kurumlarından oluşan ortak bir konsorsiyum, birleşik ağaçlandırma çabalarının bozulmuş ekosistemlerde on milyar yerli fidan diktiğini doğruladı.",
      },
      {
        en: "Satellite telemetry data reveals that canopy density in designated biodiversity corridors has regenerated by eighteen percent over the preceding five years.",
        tr: "Uydu telemetri verileri, belirlenen biyoçeşitlilik koridorlarındaki ağaç örtüsü yoğunluğunun önceki beş yılda yüzde on sekiz oranında yenilendiğini ortaya koyuyor.",
      },
      {
        en: "Ecologists argue that continuous soil monitoring and local community stewardship remain indispensable prerequisites for sustained forest resilience.",
        tr: "Ekolojistler, sürekli toprak takibi ve yerel topluluk gözetiminin sürdürülebilir orman direnci için vazgeçilmez ön koşullar olduğunu savunuyorlar.",
      },
    ],
    keyVocab: [
      { en: "indigenous saplings", tr: "yerli fidanlar" },
      { en: "telemetry", tr: "uzaktan ölçüm verisi" },
      { en: "stewardship", tr: "sorumlu yönetim/gözetim" },
    ],
  },
  {
    id: "news-03",
    category: "Bilim",
    titleEn: "Deep-Sea Expedition Discovers Thriving Ecosystem Near Hydrothermal Vents",
    titleTr: "Derin Deniz Seferi Hidrotermal Bacaların Yakınında Canlı Bir Ekosistem Keşfetti",
    date: "28 Eylül 2026",
    readTime: "3 dk okuma",
    cefrLevel: "B2",
    paragraphs: [
      {
        en: "Oceanographers deploying autonomous submersibles in the Mariana Trench have cataloged twenty-four previously undocumented marine organisms flourishing in extreme hydrothermal conditions.",
        tr: "Mariana Çukuru'na otonom denizaltılar indiren oşinograflar, aşırı hidrotermal koşullarda gelişen ve daha önce belgelenmemiş yirmi dört deniz canlısını katalogladılar.",
      },
      {
        en: "These species utilize chemosynthesis rather than solar radiation, metabolizing mineral-rich sulfide fluids emitted directly from the planetary crust.",
        tr: "Bu türler güneş ışınımı yerine kemosentez kullanarak doğrudan gezegen kabuğundan yayılan mineral bakımından zengin sülfür sıvılarını metabolize ediyorlar.",
      },
    ],
    keyVocab: [
      { en: "autonomous submersible", tr: "otonom denizaltı" },
      { en: "chemosynthesis", tr: "kemosentez (kimyasal enerjiyle beslenme)" },
      { en: "planetary crust", tr: "gezegen kabuğu" },
    ],
  },
  {
    id: "news-04",
    category: "Ekonomi",
    titleEn: "Central Banks Accelerate Cross-Border Digital Currency Interoperability",
    titleTr: "Merkez Bankaları Sınır Ötesi Dijital Para Birlikte Çalışabilirliğini Hızlandırıyor",
    date: "27 Eylül 2026",
    readTime: "4 dk okuma",
    cefrLevel: "C1",
    paragraphs: [
      {
        en: "A multilateral framework established by major financial authorities aims to standardize cross-border settlements, substantially reducing transaction latency and intermediary fees.",
        tr: "Büyük finans otoriteleri tarafından kurulan çok taraflı bir çerçeve, sınır ötesi ödemeleri standartlaştırmayı ve işlem gecikmesi ile aracı ücretlerini önemli ölçüde azaltmayı hedefliyor.",
      },
      {
        en: "Economists contend that frictionless liquidity flows could augment global trade volumes among emerging economies by as much as four hundred billion dollars annually.",
        tr: "Ekonomistler, sürtünmesiz likidite akışlarının gelişmekte olan ekonomiler arasındaki küresel ticaret hacmini yılda dört yüz milyar dolara kadar artırabileceğini savunuyorlar.",
      },
    ],
    keyVocab: [
      { en: "interoperability", tr: "birlikte çalışabilirlik" },
      { en: "transaction latency", tr: "işlem gecikmesi süresi" },
      { en: "emerging economies", tr: "gelişmekte olan ekonomiler" },
    ],
  },
];

export default function HaberlerPage() {
  const [selectedCategory, setSelectedCategory] = useState<string>("Tümü");
  const [activeArticle, setActiveArticle] = useState<NewsArticle>(SAMPLE_NEWS[0]!);
  const [searchQuery, setSearchQuery] = useState("");
  const [voiceGender, setVoiceGender] = useState<"kadin" | "erkek">("kadin");
  const [isPlaying, setIsPlaying] = useState(false);
  const [revealedTranslations, setRevealedTranslations] = useState<Record<number, boolean>>({});

  const categories = ["Tümü", "Teknoloji", "İklim & Çevre", "Bilim", "Ekonomi", "Kültür", "Sağlık"];

  const filteredNews = SAMPLE_NEWS.filter((item) => {
    const matchesCat = selectedCategory === "Tümü" || item.category === selectedCategory;
    const matchesQuery =
      item.titleEn.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.titleTr.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCat && matchesQuery;
  });

  // Sesli Dinleme (Doğal Ses + MediaSession Arka Planda Çalma)
  const togglePlayAudio = () => {
    if (typeof window === "undefined" || !("speechSynthesis" in window)) {
      alert("Cihazınız ses sentezini desteklemiyor.");
      return;
    }

    if (isPlaying) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
      return;
    }

    window.speechSynthesis.cancel();

    // Haberi baştan sona İngilizce oku
    const textToRead = `${activeArticle.titleEn}. ${activeArticle.paragraphs.map((p) => p.en).join(" ")}`;

    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.lang = "en-GB";
    utterance.rate = 0.95;

    const voices = window.speechSynthesis.getVoices();
    if (voiceGender === "kadin") {
      const fVoice = voices.find((v) => v.lang.startsWith("en") && (v.name.includes("Female") || v.name.includes("Samantha") || v.name.includes("Victoria") || v.name.includes("Google UK English Female")));
      if (fVoice) utterance.voice = fVoice;
      utterance.pitch = 1.05;
    } else {
      const mVoice = voices.find((v) => v.lang.startsWith("en") && (v.name.includes("Male") || v.name.includes("Daniel") || v.name.includes("Oliver") || v.name.includes("Google UK English Male")));
      if (mVoice) utterance.voice = mVoice;
      utterance.pitch = 0.88;
    }

    utterance.onstart = () => {
      setIsPlaying(true);

      // 📱 TELEFON EKRANI KAPANINCA ÇALMAYA DEVAM ET
      if ("mediaSession" in navigator) {
        navigator.mediaSession.metadata = new MediaMetadata({
          title: activeArticle.titleEn,
          artist: `IELTS Akademi Haberleri · ${voiceGender === "kadin" ? "Kadın Spiker (Emily)" : "Erkek Spiker (James)"}`,
          album: `Gündem İngilizce · ${activeArticle.category}`,
          artwork: [
            { src: "/img/logo.svg", sizes: "512x512", type: "image/svg+xml" },
          ],
        });

        navigator.mediaSession.setActionHandler("play", () => {
          window.speechSynthesis.resume();
          setIsPlaying(true);
        });
        navigator.mediaSession.setActionHandler("pause", () => {
          window.speechSynthesis.pause();
          setIsPlaying(false);
        });
      }
    };

    utterance.onend = () => {
      setIsPlaying(false);
      addStudentXp(20, "okuma");
    };

    utterance.onerror = () => {
      setIsPlaying(false);
    };

    window.speechSynthesis.speak(utterance);
  };

  useEffect(() => {
    return () => {
      if (typeof window !== "undefined" && "speechSynthesis" in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, [activeArticle]);

  const toggleSentenceTranslation = (idx: number) => {
    setRevealedTranslations((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  return (
    <div className="min-h-screen py-8 px-4 sm:px-6">
      <div className="mx-auto max-w-6xl space-y-8">
        {/* Üst Başlık & Bilgilendirme */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="inline-flex items-center gap-1.5 rounded-full bg-blue-100 px-3 py-1 text-xs font-black text-blue-800 dark:bg-blue-950 dark:text-blue-300">
              <Newspaper className="h-3.5 w-3.5" />
              2,000+ Gündem İngilizce Haberler & Dinleme Modülü
            </div>
            <h1 className="mt-2 text-3xl font-black tracking-tight text-slate-900 dark:text-white">
              Gündem İngilizce Haberleri 🌍
            </h1>
            <p className="mt-1 text-xs sm:text-sm text-slate-500 dark:text-slate-400">
              Gerçek akademik dünya gündemini okuyun, kadın veya erkek spiker sesiyle arka planda dinleyin ve cümlelere tıklayarak anında Türkçe çevirisini öğrenin.
            </p>
          </div>

          {/* Arama Kutusu */}
          <div className="relative">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Haber veya konu ara..."
              className="w-full sm:w-64 rounded-2xl border border-slate-200 bg-white px-4 py-2 pl-9 text-xs font-medium text-slate-900 outline-none transition focus:border-blue-500 dark:border-slate-800 dark:bg-[#121212] dark:text-white"
            />
            <Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-400" />
          </div>
        </div>

        {/* Kategori Filtresi */}
        <div className="flex overflow-x-auto gap-2 rounded-2xl border border-slate-200 bg-white/90 p-2 dark:border-slate-800 dark:bg-[#0c0c0c] no-scrollbar">
          {categories.map((cat) => (
            <button
              key={cat}
              type="button"
              onClick={() => setSelectedCategory(cat)}
              className={`shrink-0 rounded-xl px-4 py-2 text-xs font-black transition-all ${
                selectedCategory === cat
                  ? "bg-blue-600 text-white shadow-sm"
                  : "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Ana İçerik Grid Düzeni (Sol: Okuma & Dinleme / Sağ: Haber Listesi) */}
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
          {/* Sol Kolon: Seçili Haberi Oku, Dinle ve Çevir */}
          <div className="lg:col-span-8 space-y-6">
            <div className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-xl dark:border-slate-800 dark:bg-[#0e0e0e] sm:p-8">
              <div className="rainbow-gradient-h absolute top-0 inset-x-0 h-1.5" />

              {/* Üst Metadata */}
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-4 dark:border-slate-800 text-xs text-slate-400 font-semibold">
                <div className="flex items-center gap-2">
                  <span className="rounded-full bg-blue-100 px-2.5 py-0.5 text-[10px] font-black text-blue-700 dark:bg-blue-950 dark:text-blue-300 uppercase">
                    {activeArticle.category}
                  </span>
                  <span className="rounded-full bg-purple-100 px-2.5 py-0.5 text-[10px] font-black text-purple-700 dark:bg-purple-950 dark:text-purple-300">
                    CEFR {activeArticle.cefrLevel}
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  <span className="flex items-center gap-1">
                    <Calendar className="h-3.5 w-3.5" /> {activeArticle.date}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="h-3.5 w-3.5" /> {activeArticle.readTime}
                  </span>
                </div>
              </div>

              {/* Başlık */}
              <h2 className="mt-4 text-xl sm:text-2xl font-black text-slate-900 dark:text-white leading-tight">
                {activeArticle.titleEn}
              </h2>
              <p className="mt-1 text-xs sm:text-sm font-bold text-slate-500 dark:text-slate-400">
                🇹🇷 {activeArticle.titleTr}
              </p>

              {/* Sesli Çalma Çubuğu */}
              <div className="my-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-[#141414]">
                <div className="flex items-center gap-2">
                  <Headphones className="h-5 w-5 text-blue-600" />
                  <div>
                    <p className="text-xs font-black text-slate-800 dark:text-slate-200">
                      Doğal Sesli Haber Dinleyicisi
                    </p>
                    <p className="text-[10px] text-slate-400">
                      📱 Ekran kilitlense bile arka planda çalmaya devam eder.
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  {/* Kadın/Erkek Seçimi */}
                  <div className="flex rounded-xl bg-slate-200 p-0.5 text-[10px] font-bold dark:bg-slate-800">
                    <button
                      type="button"
                      onClick={() => setVoiceGender("kadin")}
                      className={`rounded-lg px-2 py-1 transition-all ${
                        voiceGender === "kadin" ? "bg-white text-slate-900 shadow-sm dark:bg-[#222] dark:text-white" : "text-slate-500"
                      }`}
                    >
                      👩 Kadın
                    </button>
                    <button
                      type="button"
                      onClick={() => setVoiceGender("erkek")}
                      className={`rounded-lg px-2 py-1 transition-all ${
                        voiceGender === "erkek" ? "bg-white text-slate-900 shadow-sm dark:bg-[#222] dark:text-white" : "text-slate-500"
                      }`}
                    >
                      👨 Erkek
                    </button>
                  </div>

                  <button
                    type="button"
                    onClick={togglePlayAudio}
                    className={`flex items-center gap-1.5 rounded-xl px-4 py-2 text-xs font-black text-white transition-all shadow-md ${
                      isPlaying
                        ? "bg-rose-600 animate-pulse hover:bg-rose-700"
                        : "bg-gradient-to-r from-blue-600 to-indigo-600 hover:opacity-95"
                    }`}
                  >
                    {isPlaying ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
                    <span>{isPlaying ? "Durdur" : "Haberi Dinle"}</span>
                  </button>
                </div>
              </div>

              {/* Paragraflar (Tıklanabilir Türkçe Çeviri) */}
              <div className="space-y-4">
                <p className="text-[11px] font-bold text-slate-400">
                  💡 İpucu: Anlamadığınız cümlenin üzerine tıklayarak Türkçe çevirisini anında görebilirsiniz.
                </p>

                {activeArticle.paragraphs.map((p, idx) => (
                  <div
                    key={idx}
                    onClick={() => toggleSentenceTranslation(idx)}
                    className="cursor-pointer rounded-2xl border border-slate-100 bg-slate-50/50 p-4 transition-all hover:border-blue-400 hover:bg-blue-50/20 dark:border-slate-800/80 dark:bg-[#121212] dark:hover:bg-[#181818]"
                  >
                    <p className="text-sm sm:text-base font-medium text-slate-800 dark:text-slate-200 leading-relaxed">
                      {p.en}
                    </p>

                    <div className="mt-2 flex items-center justify-between text-xs text-blue-600 dark:text-blue-400 font-bold">
                      <span className="flex items-center gap-1">
                        <Languages className="h-3.5 w-3.5" />
                        <span>{revealedTranslations[idx] ? "Türkçeyi Gizle" : "🇹🇷 Türkçe Çeviriyi Gör (Tıkla)"}</span>
                      </span>
                      {revealedTranslations[idx] ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
                    </div>

                    {revealedTranslations[idx] && (
                      <div className="mt-2.5 rounded-xl bg-amber-500/10 p-3 text-xs leading-relaxed text-amber-950 border border-amber-500/20 dark:text-amber-200 animate-fadeIn">
                        {p.tr}
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {/* Anahtar Kelimeler (Vocabulary Vault) */}
              <div className="mt-8 border-t border-slate-100 pt-5 dark:border-slate-800">
                <p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-2">
                  📚 Haberde Geçen Kritik Akademik Kelimeler
                </p>
                <div className="flex flex-wrap gap-2">
                  {activeArticle.keyVocab.map((v, i) => (
                    <span
                      key={i}
                      className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-bold text-slate-800 dark:border-slate-800 dark:bg-[#161616] dark:text-slate-200"
                    >
                      <strong className="text-blue-600 dark:text-blue-400">{v.en}</strong>: <span>{v.tr}</span>
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Sağ Kolon: Gündem Haber Listesi */}
          <div className="lg:col-span-4 space-y-3">
            <h3 className="font-black text-sm text-slate-900 dark:text-white uppercase tracking-wider">
              En Çok Okunan Haberler ({filteredNews.length})
            </h3>

            {filteredNews.map((news) => (
              <button
                key={news.id}
                type="button"
                onClick={() => {
                  setActiveArticle(news);
                  setRevealedTranslations({});
                  setIsPlaying(false);
                }}
                className={`w-full rounded-2xl border p-4 text-left transition-all ${
                  activeArticle.id === news.id
                    ? "border-blue-500 bg-blue-50/60 text-blue-950 shadow-md dark:border-blue-500 dark:bg-blue-950/30 dark:text-blue-100"
                    : "border-slate-200 bg-white hover:border-slate-300 dark:border-slate-800 dark:bg-[#101010] dark:hover:border-slate-700"
                }`}
              >
                <div className="flex items-center justify-between text-[10px] font-bold text-slate-400 mb-1">
                  <span className="uppercase">{news.category}</span>
                  <span className="rounded bg-black/10 px-1.5 py-0.5 font-black">{news.cefrLevel}</span>
                </div>
                <h4 className="text-xs sm:text-sm font-bold line-clamp-2 leading-snug">
                  {news.titleEn}
                </h4>
                <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400 line-clamp-1">
                  {news.titleTr}
                </p>
                <div className="mt-2.5 flex items-center justify-between text-[10px] font-semibold text-slate-400">
                  <span>{news.date}</span>
                  <span className="flex items-center gap-1 text-blue-600 dark:text-blue-400 font-bold">
                    <span>Oku & Dinle</span>
                    <ArrowRight className="h-3 w-3" />
                  </span>
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
